DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS STAFF;
DROP TABLE IF EXISTS RECEIPT;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS VENDOR;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ORDERLINE;

CREATE TABLE CUSTOMER(
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(250) NOT NULL);

CREATE TABLE STAFF
(
    staffname VARCHAR2(50) not null,
    lastname VARCHAR2(50) not null,
    address VARCHAR2(50),
    cellnumber VARCHAR2(50) not null unique,
    email VARCHAR2(50) not null unique,
    STAFFID VARCHAR2(50) not null unique

);

CREATE TABLE RECEIPT
(
);

CREATE TABLE PRODUCTS
(
);

CREATE TABLE VENDOR
(
    name VARCHAR2(50) not null,
    cellnumber VARCHAR2(50),
    address VARCHAR2(50),
    vendorID VARCHAR2(50) not null unique,
    email VARCHAR2(50) not null
);

CREATE TABLE ORDERS
(
);

CREATE TABLE ORDERLINE
(
);